name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - matplotlib.pyplot
  - seaborn
  - cufflinks
  - plotly.graph_objects
  - chart_studio.plotly
  - plotly.express 
  - ipywidgets
  - plotly.io 
  - folium
  - voila

